when@dev:
    api:
        resource: ../../../src/Controller/
        type: attribute
    api_infrastructure:
        resource: ../../../src/Infrastructure/Api/Controller/
        type: attribute
    api_swagger_ui:
        path: /api/doc
        controller: nelmio_api_doc.controller.stoplight
        methods: [GET]
        defaults:
            area: default
    api_openapi:
        path: /api/doc.json
        controller: nelmio_api_doc.controller.swagger_json
        methods: [GET]