controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_infrastructure:
    resource: ../src/Infrastructure/Api/Controller/
    type: attribute
