#!/usr/bin/env bash
#
# Verdict publication check for the AI code review workflow (task 5.19A).
#
# A green "OpenRabbit Review" check does not prove that a verdict exists: the
# review action can exit 0 having published nothing, or having published a review
# whose body carries no verdict at all. That was observed on PR #84, where the
# bot's review body was only "Automated PR review generated by OpenRabbit." with
# no "### Verdict" line, while the job was green; PR #85 and #86 from the same
# action did carry the line. On a fork pull request the action is expected to
# publish nothing, because the LLM secret is unavailable. This script makes the
# difference visible on the pull request, so that "no verdict" cannot pass for an
# approval.
#
# It is deliberately advisory and always exits 0 - including on an unexpected
# internal error, which is why an EXIT trap converts any non-zero status into a
# warning. The required status check is where a missing verdict has to bite (task
# 5.18); failing here would block the merge forever on a wording change in a
# third-party action, because that action's body format is not a contract.
#
# A cancelled or timed-out run never reaches this script at all, because a job
# that is killed runs no further steps - detecting those is task 5.19B, not this
# one.
#
# Usage:
#   scripts/verify-review-verdict.sh [--probe] <pull-number> <head-sha> <owner/repo>
#
# Modes:
#   (default)  advisory: reports a missing verdict as a sticky comment plus a
#              warning annotation, and always exits 0.
#   --probe    machine-readable: writes `verdict=published|missing|unverified`
#              to $GITHUB_OUTPUT so a later step can react to it, and writes no
#              comment. This is what decides whether the fallback provider has to
#              run: the review action can exit 0 having published nothing, so the
#              fallback must be keyed on publication, not on the exit code.
#
# Environment:
#   GH_TOKEN          token for the API calls (the workflow passes GITHUB_TOKEN)
#   GITHUB_OUTPUT     probe mode writes its result here (set by the runner)
#   VERDICT_ATTEMPTS  API attempts before concluding "not published" (default 5)
#   VERDICT_DELAY     seconds between attempts (default 10)
#
set -euo pipefail

# The mode is read before anything else: a string comparison cannot fail, and
# the trap below has to know whether it must leave a result behind.
mode='advisory'
if [ "${1:-}" = '--probe' ]; then
    mode='probe'
    shift
fi

verdict_emitted='false'

# Writes the probe result exactly once. The output drives a workflow condition,
# where an empty string is not a neutral value: `verdict != 'published'` would
# be true and the fallback would run. That fail-open outcome is deliberate, but
# it has to follow from what the check found rather than from how the script
# happened to die, so the trap calls this too.
emit_verdict() {
    if [ "${mode}" != 'probe' ] || [ "${verdict_emitted}" != 'false' ]; then
        return 0
    fi

    verdict_emitted='true'
    if [ -n "${GITHUB_OUTPUT:-}" ]; then
        printf 'verdict=%s\n' "${1:-unverified}" >>"${GITHUB_OUTPUT}" || true
    fi
    printf 'probe: verdict=%s\n' "${1:-unverified}" || true
}

# The advisory contract outranks any internal error: this script runs inside a
# required status check, so an unexpected failure would block every merge. Any
# non-zero status is therefore reported and swallowed. The trap also covers the
# `set -e` exits below, which is the point of having it. It is installed before
# the argument checks so that even a misuse (missing argument) exits 0 - in probe
# mode as `unverified`, the same fail-open branch as an unreadable API.
on_exit() {
    local status=$?
    if [ "${mode}" = 'probe' ]; then
        emit_verdict 'unverified'
    elif [ "${status}" -ne 0 ]; then
        printf '::warning::The verdict check aborted with status %s; the verdict is unverified.\n' "${status}" || true
    fi
    exit 0
}
trap on_exit EXIT

usage='usage: verify-review-verdict.sh [--probe] <pull-number> <head-sha> <owner/repo>'
pull_number="${1:?${usage}}"
head_sha="${2:?${usage}}"
repository="${3:?${usage}}"

# Non-numeric overrides would make seq/sleep fail and, without the trap, fail the
# job; normalise them here so a typo degrades into the defaults.
attempts="${VERDICT_ATTEMPTS:-5}"
delay="${VERDICT_DELAY:-10}"
case "${attempts}" in '' | *[!0-9]*) attempts=5 ;; esac
case "${delay}" in '' | *[!0-9]*) delay=10 ;; esac
[ "${attempts}" -ge 1 ] || attempts=1

# The bot is the only review author this check has to trust, and the head SHA is
# what makes a verdict current: a review left on a superseded commit says nothing
# about the code that is about to be merged.
review_author='github-actions[bot]'

# The verdict line the action writes. It is a heuristic, not a contract: a
# missing line produces an advisory warning, never a failure, so a wording change
# in the action degrades this check instead of blocking the merge.
verdict_marker='### Verdict'

# The marker carries the head SHA, so a stale warning about an older commit is
# never rewritten into a claim about the current one. Task 5.19B reserves the
# distinct prefix `opencode-verdict-cancelled` for the cancelled/timed-out
# detector, so the two never collide.
marker="<!-- opencode-verdict-missing ${head_sha} -->"

summary() {
    if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
        printf '%s\n' "$1" >>"${GITHUB_STEP_SUMMARY}" 2>/dev/null || true
    fi
}

# An annotation surfaces in the pull request's checks UI, which is where a human
# actually looks; a summary line alone is easy to miss.
warn() {
    printf '::warning::%s\n' "$1" || true
    summary "**Warning:** $1"
}

# The reviews list is eventually consistent: the action publishes its review as
# the last thing it does, and the API can still lag behind that write. A single
# read would report a false "no verdict" often enough to make this check noise.
#
# Only the matching review ids are printed, one per line: gh applies --jq per
# page and does not accept --slurp alongside it (gh 2.96.0 rejects the pair), so
# the pages cannot be merged into one array here. Presence of any output is the
# signal, which needs no arithmetic and stays correct across pages.
verdict_reviews() {
    gh api --paginate "repos/${repository}/pulls/${pull_number}/reviews" \
        --jq ".[] | select(.user.login == \"${review_author}\" and .commit_id == \"${head_sha}\" and ((.body // \"\") | contains(\"${verdict_marker}\"))) | .id"
}

# Same query without the verdict condition, used only to tell "published a review
# without a verdict" apart from "published nothing" in the warning text.
reviews_on_head() {
    gh api --paginate "repos/${repository}/pulls/${pull_number}/reviews" \
        --jq ".[] | select(.user.login == \"${review_author}\" and .commit_id == \"${head_sha}\") | .id"
}

# Warning comments this check left for this head, authored by the bot.
existing_warning_ids() {
    gh api --paginate "repos/${repository}/issues/${pull_number}/comments" \
        --jq ".[] | select(.user.login == \"${review_author}\" and ((.body // \"\") | contains(\"${marker}\"))) | .id"
}

verdicts=''
api_ok='false'
for attempt in $(seq 1 "${attempts}"); do
    if verdicts="$(verdict_reviews)"; then
        api_ok='true'
        if [ -n "${verdicts}" ]; then
            break
        fi
    else
        verdicts=''
    fi

    if [ "${attempt}" -lt "${attempts}" ]; then
        sleep "${delay}"
    fi
done

# Probe mode stops here: the caller decides what a missing verdict means, and
# the answer is deliberately three-valued. "Could not read" is not "not
# published" - it is "unknown", and the fallback is allowed to run for an unknown
# state instead of only for a proven absence.
if [ "${mode}" = 'probe' ]; then
    if [ "${api_ok}" != 'true' ]; then
        emit_verdict 'unverified'
    elif [ -n "${verdicts}" ]; then
        emit_verdict 'published'
    else
        emit_verdict 'missing'
    fi

    exit 0
fi

if [ "${api_ok}" = 'true' ] && [ -n "${verdicts}" ]; then
    count="$(printf '%s\n' "${verdicts}" | wc -l | tr -d ' ')"
    echo "verdict: published (${count} review(s) on ${head_sha})"

    # A verdict can arrive later, on a re-run of the review workflow - which is
    # exactly what the warning tells the reader to do. Leaving the warning behind
    # would make the signal contradict itself, so clear this head's warnings. A
    # refusal to delete is reported but never fails the step.
    #
    # If the lookup itself fails, this block is skipped silently and the warning
    # stays until the next run: that is the intended trade - a stale advisory note
    # is better than a false "cleared" claim, and the next run re-checks.
    if resolved_ids="$(existing_warning_ids)"; then
        printf '%s\n' "${resolved_ids}" | while IFS= read -r resolved_id; do
            if [ -z "${resolved_id}" ]; then
                continue
            fi

            if gh api --method DELETE "repos/${repository}/issues/comments/${resolved_id}" >/dev/null 2>&1; then
                echo "verdict: cleared the earlier warning comment ${resolved_id}"
            else
                warn "A verdict was published for ${head_sha}, but clearing the earlier warning comment ${resolved_id} failed."
            fi
        done
    fi

    summary "A verdict for \`${head_sha}\` was published by the review bot."
    exit 0
fi

# An unreadable list is not the same finding as a missing verdict, and reporting
# it as one would be a false accusation against the review.
if [ "${api_ok}" != 'true' ]; then
    warn "Could not read the review list for ${head_sha}: the verdict is unverified, not missing."
    exit 0
fi

# Best effort, and only on the warning path: was a review published at all? If
# this second read fails (the list was readable moments ago, so a transient API
# failure), the wording stays neutral instead of claiming nothing was published.
review_published='false'
published_query_ok='true'
if published="$(reviews_on_head)"; then
    if [ -n "${published}" ]; then
        review_published='true'
    fi
else
    published_query_ok='false'
fi

if [ "${review_published}" = 'true' ]; then
    detail="The bot did publish a review for ${head_sha}, but its body carries no verdict line, so there is nothing to treat as an approval."
elif [ "${published_query_ok}" = 'true' ]; then
    detail="The review action published no review for ${head_sha} at all."
else
    detail="The review list could not be re-read, so it is unknown whether a review was published for ${head_sha}."
fi

body="${marker}
The AI review job finished green, but no verdict was published for ${head_sha}.

${detail}

This is not an approval. Push a new commit, or re-run the Code Review workflow, to
obtain a verdict before merging."

# Reuse the warning for this head instead of stacking one comment per run. The
# marker pins the SHA, so an older warning is left alone rather than rewritten,
# and the author filter keeps a contributor's own comment from being overwritten.
existing_ids=''
existing_ids="$(existing_warning_ids 2>/dev/null)" || existing_ids=''
existing_id="$(printf '%s\n' "${existing_ids}" | sed -n '1p')"

if [ -n "${existing_id}" ]; then
    if gh api --method PATCH "repos/${repository}/issues/comments/${existing_id}" -f body="${body}" >/dev/null 2>&1; then
        echo "verdict: missing; updated warning comment ${existing_id}"
        warn "No verdict was published for ${head_sha}; the existing warning comment was updated."
        exit 0
    fi

    warn "No verdict was published for ${head_sha}, and updating the warning comment failed."
    exit 0
fi

if gh api --method POST "repos/${repository}/issues/${pull_number}/comments" -f body="${body}" >/dev/null 2>&1; then
    echo "verdict: missing; posted a warning comment"
    warn "No verdict was published for ${head_sha}; a warning comment was posted."
    exit 0
fi

warn "No verdict was published for ${head_sha}, and posting the warning comment failed (check that the workflow may write issue comments)."
exit 0
